import React, { createContext, useContext, useState, useEffect } from "react";

export type Language = "en" | "ar";

const translations = {
  en: {
    // Brand & Top bar
    appName: "Smart Real Estate CRM",
    enterpriseCrm: "Enterprise Real Estate System",
    dashboard: "Dashboard",
    properties: "Properties",
    owners: "Owners",
    clients: "Clients",
    brokers: "Brokers",
    reminders: "Reminders",
    auditLogs: "Audit Trail",
    whatsappLogs: "WhatsApp Logs",
    logout: "Logout",
    langToggle: "العربية",
    language: "Language",
    dark: "Dark Mode",
    light: "Light Mode",

    // Auth Screen
    subtitle: "Egypt's Smart Property Marketing Solution",
    signIn: "Sign In",
    emailAddress: "Email Address",
    password: "Password",
    fastRoles: "Fast Testing Roles:",
    admin: "Admin",
    manager: "Manager",
    agent: "Sales Agent",

    // Dashboard Stats
    matchingOpportunities: "Matching Opportunities",
    totalProperties: "Total Properties",
    forSale: "For Sale",
    forRent: "For Rent",
    totalClients: "Total Clients",
    activeRequests: "Active Requests",
    totalOwners: "Total Owners",
    totalRevenue: "Total Revenue",
    recentActivities: "Recent Activities",
    topAreas: "Top Areas",
    topAgents: "Top Sales Agents",
    salesStatistics: "Sales Distribution by Property Type",
    brokerCommissions: "Broker Commissions",
    units: "Units",
    closedDeals: "Deals Closed",
    listings: "Listings",
    triggered: "triggered",
    system: "System",
    noData: "No data available",
    noAlerts: "No new alerts",
    noActivities: "No activities recorded",

    // Properties Management
    propertyType: "Property Type",
    saleRent: "Sale / Rent",
    address: "Address",
    area: "Area (sqm)",
    bedrooms: "Bedrooms",
    bathrooms: "Bathrooms",
    floorNumber: "Floor Number",
    finishing: "Finishing Type",
    furnished: "Furnished",
    price: "Price",
    status: "Status",
    available: "Available",
    sold: "Sold",
    rented: "Rented",
    addProperty: "Add Property",
    editProperty: "Edit Property",
    delete: "Delete",
    edit: "Edit",
    cancel: "Cancel",
    save: "Save",
    search: "Search...",
    filterBy: "Filter By",
    exportCsv: "Export CSV",
    print: "Print",
    allTypes: "All Types",
    allListing: "Sale or Rent",
    totalPrice: "Total Price",
    toggleStatus: "Toggle Status",
    findMatches: "Find Matches",
    noImages: "No images attached",
    uploadImages: "Upload Property Images",
    selectFiles: "Select Image Files from Device",
    clickToUpload: "Click or drag images here to upload",
    maxUploadNotice: "Upload multiple photos (JPG, PNG, WebP)",
    remove: "Remove",
    uploading: "Uploading images...",
    imagesUploaded: "Images uploaded successfully",
    noImageUploadedNotice: "No images attached to this unit",
    sqm: "sqm",
    egp: "EGP",
    floor: "Floor",
    rooms: "Rooms",
    baths: "Baths",
    selectOwner: "Select Owner",
    selectBroker: "Select Broker (Optional)",
    directListing: "Direct Listing (No Broker)",
    description: "Description & Details",
    notes: "Notes",

    // Types
    apartment: "Apartment",
    villa: "Villa",
    office: "Administrative Office",
    shop: "Commercial Shop",
    land: "Land",

    // Finishing
    superLux: "Super Lux",
    ultraLux: "Ultra Lux",
    semiFinished: "Semi Finished",
    unfinished: "Unfinished",

    // Owners Management
    ownerName: "Owner Name",
    ownerPhone: "Owner Phone",
    ownerWhatsapp: "Owner WhatsApp",
    ownerEmail: "Owner Email",
    nationalId: "National ID (Optional)",
    addOwner: "Add Owner",
    editOwner: "Edit Owner",
    ownedProperties: "Owned Properties",
    ownedUnits: "Owned Units",
    searchOwner: "Search Owner...",
    ownerId: "Owner ID",
    actions: "Actions",

    // Clients & Requirements
    clientType: "Client Type",
    pipelineStep: "Pipeline Stage",
    minBudget: "Min Budget",
    maxBudget: "Max Budget",
    minArea: "Min Area (sqm)",
    priority: "Priority",
    preferredAreas: "Preferred Areas",
    addClient: "Add Client",
    editClient: "Edit Client",
    buyer: "Buyer",
    tenant: "Tenant",
    investor: "Investor",
    newLead: "New Lead",
    interested: "Interested",
    negotiating: "Negotiating",
    closed: "Closed",
    lost: "Lost",
    high: "High",
    medium: "Medium",
    low: "Low",
    yes: "Yes",
    no: "No",
    all: "All",
    allClients: "All Clients",
    lookingFor: "Client is looking for",
    targetType: "Target Property Type",
    preferredAreasHelper: "Preferred Areas (comma separated)",
    mustFurnished: "Must be Furnished",
    additionalPreferences: "Additional Preferences",
    searchClient: "Search Client or Area...",
    autoCurrentUser: "Auto (Current User)",
    sourceBroker: "Source Broker (Optional)",
    basicInfo: "1. Basic Customer Info",
    requirementsProfiling: "2. Requirements Profiling",
    budget: "Budget",
    openBudget: "Open",
    pipelineUpdated: "Client pipeline stage updated",

    // Brokers Management
    addBroker: "Add Broker",
    editBroker: "Edit Broker",
    brokerAgencyName: "Broker / Agency Name",
    commissionPct: "Commission %",
    dealsClosed: "Deals Closed",
    earnings: "Earnings",
    externalBrokerWarning: "Allow external brokers to list properties and refer clients.",
    commissionReports: "Broker Commissions",
    commissionRate: "Commission Rate",
    searchBroker: "Search Broker...",
    deals: "Deals",

    // Reminders
    remindersTitle: "Title",
    remindersTime: "Time",
    addReminder: "Add Reminder",
    scheduledTasks: "Scheduled Tasks & Follow-ups",
    scheduledTasksDesc: "Reminders, follow-up calls, and calendar schedules",
    noReminders: "No scheduled reminders at the moment",
    bindClientOptional: "Link to Client (Optional)",
    scheduleTime: "Scheduled Date & Time",
    descriptionMemo: "Description / Notes",
    reminderCompleted: "Reminder marked completed",
    pending: "Pending",
    completed: "Completed",
    overdue: "Overdue",

    // Smart Matching Engine
    viewMatches: "View Matches",
    matchScore: "Match Score",
    score: "Score",
    matchReason: "Match Breakdown",
    locationMatch: "Location",
    budgetMatch: "Budget",
    areaMatch: "Area",
    roomsMatch: "Bedrooms",
    furnishedMatch: "Furnishing",
    sendWhatsApp: "Send WhatsApp Alert",
    closeDrawer: "Close Drawer",
    noMatches: "No matching properties found for this client.",
    noMatchesFound: "No matches found at this time.",

    // WhatsApp System
    whatsappSimulator: "WhatsApp Notification Center",
    templates: "Message Templates",
    arabicTemplate: "Arabic Template",
    englishTemplate: "English Template",
    saveTemplate: "Save Template",
    deliveryLogs: "Delivery Logs",
    sendManual: "Open WhatsApp Web",
    sendAuto: "Send Notification",
    templateUpdated: "Template updated successfully",
    templateVariablesNotice: "Available placeholders: {clientName}, {type}, {location}, {price}, {area}, {bedrooms}, {link}",
    timestamp: "Timestamp",
    clientName: "Client Name",
    whatsappPhone: "WhatsApp Number",
    messageText: "Message Text",
    deliveryStatus: "Delivery Status",
    sent: "Sent",
    failed: "Failed",
    noLogs: "No message logs recorded",
    dealClosedSuccess: "WhatsApp message compiled successfully",

    // Interactive Dashboard Card Modals & Actions
    clickForDetails: "Click to view full details",
    allMatchingPairs: "All Smart Matching Opportunities",
    allMatchingPairsDesc: "Automatically detected matches between customer requirements and available listings",
    dealsRevenueDetails: "Revenue & Closed Deals Breakdown",
    dealsRevenueDetailsDesc: "List of closed sales & rental deals with earned commissions",
    dealAmount: "Deal Value",
    closeModal: "Close",
    clientLooking: "Customer Request",
    matchedUnit: "Matched Listing",

    // Audit Trail
    systemAuditTrail: "System Audit Trail",
    auditTrailDesc: "Comprehensive log recording user actions, timestamps, and payload data",
    userName: "User Name",
    actionCode: "Action Code",
    payloadDetails: "Payload Details",

    // User Management (Admin)
    usersManagement: "Users & Permissions",
    usersManagementDesc: "Create and manage system user accounts, roles, and administrative permissions",
    addUser: "Add New User",
    editUser: "Edit User",
    deleteUserConfirm: "Are you sure you want to delete this user?",
    roleAdmin: "Admin (Full Access)",
    roleManager: "Sales Manager",
    roleAgent: "Sales Agent",
    roleAdminDesc: "Full administrative control, user creation, financial reports, WhatsApp and system settings",
    roleManagerDesc: "Manage listings, clients, owners, brokers, matching, pipeline and sales performance",
    roleAgentDesc: "Add and follow up assigned properties, clients, requirements and WhatsApp alerts",
    userRole: "Role & Permissions",
    phoneOptional: "Phone (Optional)",
    passwordLabel: "Password",
    passwordEditHint: "Leave blank to keep current password",
    totalUsersCount: "Total Team Members",
    adminsCount: "Admins",
    managersCount: "Managers",
    agentsCount: "Agents",
    customPermissions: "Custom Granular Permissions",
    customPermissionsDesc: "Fine-tune and assign individual feature access permissions for this user",
    selectAllPerms: "Select All Permissions",
    deselectAllPerms: "Deselect All",
    perm_properties: "Manage Properties (Add / Edit / Delete)",
    perm_clients: "Manage Clients, Requests & Pipeline",
    perm_owners: "Manage Owners & Contacts",
    perm_brokers: "Manage External Brokers",
    perm_deals: "Close Deals & Update Property Status",
    perm_revenue: "View Financials & Net Revenue Reports",
    perm_whatsapp: "Send WhatsApp Alerts & Manage Templates",
    perm_reminders: "Manage Reminders & Tasks",
    perm_audit: "View System Audit Trail",
    perm_users: "Manage Users & Permissions (Admin)",

    // Deal Closing & Commission Management
    closeDealTitle: "Close Deal & Document Commission",
    closeDealDesc: "Specify selling price, channel (Direct / Broker), total commission, and broker share to calculate net revenue",
    actualDealPrice: "Actual Deal Price / Rent",
    saleChannel: "Sale / Deal Channel",
    directDeal: "Direct by Our Company",
    externalBrokerDeal: "Through External Broker / Partner",
    selectBuyerTenant: "Select Buyer / Tenant (Optional)",
    buyerTenantName: "Client / Buyer Name",
    companyCommissionGross: "Total Deal Commission",
    commissionPctOrAmount: "Commission Calculation Method",
    percentage: "Percentage (%)",
    fixedAmount: "Fixed Amount (EGP)",
    externalBrokerShare: "External Broker Share / Payout",
    brokerSharePctOrAmount: "Broker Share Calculation",
    netCompanyRevenue: "Net Company Profit (Inflow)",
    netCompanyRevenueDesc: "Actual revenue entering the company after deducting external broker payout",
    confirmCloseDeal: "Confirm Deal & Update Unit Status",
    grossCommissionLabel: "Gross Commission",
    brokerPayoutLabel: "Broker Share",
    netProfitLabel: "Net Profit",
    directSaleBadge: "Direct Deal",
    brokerSaleBadge: "Broker Deal",
    dealNotesPlaceholder: "Any remarks regarding the contract or commission breakdown...",
    contractType: "Contract Type",
    dealSoldSuccess: "Deal recorded and unit status updated successfully!",
    dealSalesAgent: "Closing Sales Agent (Sales Attribution)",
    dealSalesAgentDesc: "Select the sales agent who worked on this deal to calculate their commissions and performance",
    dealClosedBySelf: "Closed by myself directly (Admin/Manager direct)",

    // Notification Center & Actions
    notificationCenter: "Actionable Notification Center",
    notificationsDesc: "Real-time system alerts and tasks requiring action",
    viewMatchesAction: "Review Smart Matches ⚡",
    viewRemindersAction: "Open Reminders & Tasks 📅",
    viewClientsAction: "View Client Pipeline 👥",
    viewDealsAction: "View Closed Deals 💰",
    newMatchesAlertTitle: "Smart Matching Opportunities",
    pendingRemindersAlertTitle: "Pending Reminders & Tasks",
    activeClientsAlertTitle: "Active Clients in Pipeline",
    newDealsAlertTitle: "Recently Closed Deals",
    allCaughtUp: "All tasks completed! No pending alerts.",
  },
  ar: {
    // Brand & Top bar
    appName: "سمارت العقاري CRM",
    enterpriseCrm: "نظام إدارة وتسويق العقارات الذكي",
    dashboard: "لوحة التحكم",
    properties: "العقارات",
    owners: "الملاك",
    clients: "العملاء",
    brokers: "الوسطاء (البروكار)",
    reminders: "التذكيرات",
    auditLogs: "سجل العمليات",
    whatsappLogs: "سجل الواتساب",
    logout: "تسجيل الخروج",
    langToggle: "English",
    language: "اللغة",
    dark: "الوضع الداكن",
    light: "الوضع المضيء",

    // Auth Screen
    subtitle: "الحل الذكي المتكامل لإدارة وتسويق العقارات في مصر",
    signIn: "تسجيل الدخول",
    emailAddress: "البريد الإلكتروني",
    password: "كلمة المرور",
    fastRoles: "أدوار سريعة للتجربة:",
    admin: "المدير العام (Admin)",
    manager: "مدير المبيعات (Manager)",
    agent: "وسيط المبيعات (Agent)",

    // Dashboard Stats
    matchingOpportunities: "فرص المطابقة الذكية",
    totalProperties: "إجمالي العقارات",
    forSale: "عقارات للبيع",
    forRent: "عقارات للإيجار",
    totalClients: "إجمالي العملاء",
    activeRequests: "الطلبات النشطة",
    totalOwners: "إجمالي الملاك",
    totalRevenue: "إجمالي الإيرادات",
    recentActivities: "الأنشطة الأخيرة",
    topAreas: "أكثر المناطق طلباً",
    topAgents: "أفضل وكلاء المبيعات",
    salesStatistics: "توزيع المبيعات حسب نوع العقار",
    brokerCommissions: "عمولات الوسطاء",
    units: "وحدات",
    closedDeals: "صفقات مغلقة",
    listings: "طلبات / وحدات",
    triggered: "قام بتنفيذ",
    system: "النظام",
    noData: "لا توجد بيانات متاحة حالياً",
    noAlerts: "لا توجد تنبيهات جديدة",
    noActivities: "لا توجد أنشطة مسجلة حالياً",

    // Properties Management
    propertyType: "نوع العقار",
    saleRent: "نوع العرض (بيع / إيجار)",
    address: "العنوان بالتفصيل",
    area: "المساحة (م²)",
    bedrooms: "غرف النوم",
    bathrooms: "الحمامات",
    floorNumber: "رقم الطابق",
    finishing: "نوع التشطيب",
    furnished: "مفروش",
    price: "السعر",
    status: "الحالة",
    available: "متاح",
    sold: "تم البيع",
    rented: "تم الإيجار",
    addProperty: "إضافة عقار جديد",
    editProperty: "تعديل بيانات العقار",
    delete: "حذف",
    edit: "تعديل",
    cancel: "إلغاء",
    save: "حفظ البيانات",
    search: "بحث في العقارات...",
    filterBy: "تصفية حسب",
    exportCsv: "تصدير ملف Excel / CSV",
    print: "طباعة التقرير",
    allTypes: "جميع أنواع العقارات",
    allListing: "الكل (بيع وإيجار)",
    totalPrice: "السعر الإجمالي",
    toggleStatus: "تغيير حالة الوحدة",
    findMatches: "مطابقة العملاء",
    noImages: "لم يتم إرفاق صور",
    uploadImages: "رفع صور العقار من جهازك",
    selectFiles: "اختر ملفات الصور من جهازك",
    clickToUpload: "انقر هنا لاختيار الصور من جهازك أو اسحبها وأفلتها هنا",
    maxUploadNotice: "يمكنك رفع حتى 10 صور عالية الجودة (JPG, PNG, WebP)",
    remove: "إزالة",
    uploading: "جاري رفع الصور...",
    imagesUploaded: "تم رفع الصور بنجاح",
    noImageUploadedNotice: "لا توجد صور مرفقة لهذه الوحدة",
    sqm: "م²",
    egp: "ج.م",
    floor: "الطابق",
    rooms: "غرف",
    baths: "حمامات",
    selectOwner: "اختر المالك المسجل",
    selectBroker: "اختر الوسيط / البروكر (اختياري)",
    directListing: "إدراج مباشر (بدون وسيط)",
    description: "الوصف والمميزات",
    notes: "ملاحظات سرية / داخلية",

    // Types
    apartment: "شقة سكنية",
    villa: "فيلا مستقلة",
    office: "مكتب إداري",
    shop: "محل تجاري",
    land: "أرض",

    // Finishing
    superLux: "سوبر لوكس",
    ultraLux: "ألترا لوكس",
    semiFinished: "نصف تشطيب",
    unfinished: "بدون تشطيب",

    // Owners Management
    ownerName: "اسم المالك بالكامل",
    ownerPhone: "رقم هاتف المالك",
    ownerWhatsapp: "رقم واتساب المالك",
    ownerEmail: "البريد الإلكتروني للمالك",
    nationalId: "الرقم القومي (اختياري)",
    addOwner: "إضافة مالك جديد",
    editOwner: "تعديل بيانات المالك",
    ownedProperties: "الوحدات المملوكة",
    ownedUnits: "وحدات مسجلة",
    searchOwner: "بحث في الملاك...",
    ownerId: "كود المالك",
    actions: "الإجراءات",

    // Clients & Requirements
    clientType: "نوع العميل",
    pipelineStep: "مرحلة المتابعة في السيلز",
    minBudget: "الحد الأدنى للميزانية (ج.م)",
    maxBudget: "الحد الأقصى للميزانية (ج.م)",
    minArea: "الحد الأدنى للمساحة (م²)",
    priority: "درجة الأولوية",
    preferredAreas: "المناطق المفضلة",
    addClient: "إضافة عميل جديد",
    editClient: "تعديل بيانات العميل",
    buyer: "مشتري",
    tenant: "مستأجر",
    investor: "مستثمر",
    newLead: "عميل جديد (Lead)",
    interested: "مهتم ومتابع",
    negotiating: "مرحلة التفاوض",
    closed: "تم إغلاق الصفقة (Closed)",
    lost: "صفقة مفقودة (Lost)",
    high: "أولوية مرتفعة",
    medium: "أولوية متوسطة",
    low: "أولوية منخفضة",
    yes: "نعم",
    no: "لا",
    all: "الكل",
    allClients: "جميع العملاء",
    lookingFor: "يبحث عن",
    targetType: "نوع الوحدة المطلوبة",
    preferredAreasHelper: "المناطق المفضلة (افصل بين كل منطقة بفاصلة)",
    mustFurnished: "يشترط أن تكون مفروشة",
    additionalPreferences: "تفضيلات ومواصفات إضافية",
    searchClient: "بحث عن عميل بالاسم أو المنطقة أو الهاتف...",
    autoCurrentUser: "تلقائي (حسابي الحالي)",
    sourceBroker: "الوسيط المجلوب منه (اختياري)",
    basicInfo: "1. بيانات العميل الأساسية",
    requirementsProfiling: "2. متطلبات ومواصفات الوحدة المطلوبة",
    budget: "الميزانية",
    openBudget: "مفتوحة",
    pipelineUpdated: "تم تحديث مرحلة العميل بنجاح",

    // Brokers Management
    addBroker: "إضافة وسيط جديد",
    editBroker: "تعديل بيانات الوسيط",
    brokerAgencyName: "اسم الوسيط / شركة التسويق",
    commissionPct: "نسبة العمولة (%)",
    dealsClosed: "الصفقات المغلقة",
    earnings: "إجمالي الأرباح والعمولات",
    externalBrokerWarning: "إدارة شبكة الوسطاء والبروكرز وتتبع العمولات لكل صفقة بيع أو إيجار.",
    commissionReports: "تقرير عمولات الوسطاء",
    commissionRate: "نسبة العمولة المتفق عليها",
    searchBroker: "بحث في الوسطاء...",
    deals: "صفقات",

    // Reminders
    remindersTitle: "عنوان المهمة / التذكير",
    remindersTime: "موعد التنفيذ",
    addReminder: "إضافة تذكير / موعد اتصال",
    scheduledTasks: "المهام والاتصالات المجدولة",
    scheduledTasksDesc: "سجل التذكيرات ومتابعات العملاء والمواعيد المجدولة",
    noReminders: "لا توجد تذكيرات أو اتصالات مجدولة حالياً",
    bindClientOptional: "ربط بعميل محدد (اختياري)",
    scheduleTime: "التاريخ والوقت المحدد",
    descriptionMemo: "ملاحظات وتفاصيل التذكير",
    reminderCompleted: "تم إكمال التذكير بنجاح",
    pending: "قيد الانتظار",
    completed: "مكتمل",
    overdue: "متأخر عن الموعد",

    // Smart Matching Engine
    viewMatches: "عرض المطابقات الذكية",
    matchScore: "نسبة المطابقة",
    score: "النسبة",
    matchReason: "تفاصيل ونقاط المطابقة",
    locationMatch: "توافق الموقع",
    budgetMatch: "توافق الميزانية",
    areaMatch: "توافق المساحة",
    roomsMatch: "توافق الغرف",
    furnishedMatch: "توافق الفرش",
    sendWhatsApp: "إرسال تنبيه عبر واتساب",
    closeDrawer: "إغلاق النافذة",
    noMatches: "لم يتم العثور على عقارات مطابقة لمتطلبات هذا العميل حالياً.",
    noMatchesFound: "لا توجد وحدات مطابقة حالياً.",

    // WhatsApp System
    whatsappSimulator: "مركز إرسال وإدارة رسائل الواتساب",
    templates: "قوالب رسائل التنبيه التلقائية",
    arabicTemplate: "قالب الرسالة بالعربية",
    englishTemplate: "قالب الرسالة بالإنجليزية",
    saveTemplate: "حفظ القالب",
    deliveryLogs: "سجلات الإرسال والتسليم",
    sendManual: "فتح في واتساب ويب",
    sendAuto: "إرسال تلقائي",
    templateUpdated: "تم تحديث قالب الرسائل بنجاح",
    templateVariablesNotice: "المتغيرات المتاحة للدمج التلقائي: {clientName}، {type}، {location}، {price}، {area}، {bedrooms}، {link}",
    timestamp: "الوقت والتاريخ",
    clientName: "اسم العميل",
    whatsappPhone: "رقم الواتساب",
    messageText: "نص الرسالة",
    deliveryStatus: "حالة الإرسال",
    sent: "تم الإرسال بنجاح",
    failed: "فشل الإرسال",
    noLogs: "لا توجد سجلات رسائل مسجلة بعد",
    dealClosedSuccess: "تم تجهيز رسالة الواتساب بنجاح",

    // Interactive Dashboard Card Modals & Actions
    clickForDetails: "انقر هنا لعرض التفاصيل الكاملة",
    allMatchingPairs: "جميع فرص المطابقة الذكية",
    allMatchingPairsDesc: "قائمة المطابقات المكتشفة تلقائياً بين متطلبات العملاء والعقارات المتاحة بنسب التوافق",
    dealsRevenueDetails: "تفاصيل الإيرادات والصفقات المغلقة",
    dealsRevenueDetailsDesc: "قائمة الصفقات المنفذة للبيع والإيجار وإجمالي العمولات المحصلة",
    dealAmount: "قيمة الصفقة الإجمالية",
    closeModal: "إغلاق",
    clientLooking: "طلب ومواصفات العميل",
    matchedUnit: "الوحدة العقارية المتطابقة",

    // Audit Trail
    systemAuditTrail: "سجل العمليات والرقابة (Audit Trail)",
    auditTrailDesc: "سجل رقابي يوثق جميع العمليات والتعديلات المنفذة بواسطة المستخدمين بالتاريخ والبيانات",
    userName: "اسم المستخدم",
    actionCode: "رمز الإجراء",
    payloadDetails: "تفاصيل البيانات المعدلة",

    // User Management (Admin)
    usersManagement: "إدارة المستخدمين والصلاحيات",
    usersManagementDesc: "إنشاء وإدارة حسابات فريق العمل وتحديد أدوارهم وصلاحيات الوصول للنظام",
    addUser: "إضافة مستخدم جديد",
    editUser: "تعديل بيانات المستخدم",
    deleteUserConfirm: "هل أنت متأكد من حذف هذا المستخدم؟ لن يتمكن من تسجيل الدخول مجدداً.",
    roleAdmin: "مدير عام (Admin - كامل الصلاحيات)",
    roleManager: "مدير مبيعات (Sales Manager)",
    roleAgent: "وسيط / مسؤول مبيعات (Sales Agent)",
    roleAdminDesc: "تحكم شامل في النظام: إنشاء وحذف المستخدمين، ضبط إعدادات الواتساب، والاطلاع على الأرباح والتقارير.",
    roleManagerDesc: "إدارة العقارات والعملاء والملاك والوسطاء ومتابعة مسار المبيعات وفرص المطابقة.",
    roleAgentDesc: "إضافة ومتابعة العقارات والعملاء المسندين إليه وإرسال عروض الواتساب ومتابعة التذكيرات.",
    userRole: "الدور والصلاحية",
    phoneOptional: "رقم الهاتف (اختياري)",
    passwordLabel: "كلمة المرور",
    passwordEditHint: "اترك الحقل فارغاً إذا كنت لا ترغب في تغيير كلمة المرور الحالية",
    totalUsersCount: "إجمالي أعضاء الفريق",
    adminsCount: "المديرين العامين",
    managersCount: "مديري المبيعات",
    agentsCount: "مسؤولي المبيعات",
    customPermissions: "تخصيص الصلاحيات بالتفصيل (Granular Permissions)",
    customPermissionsDesc: "يمكنك تفعيل أو تعطيل صلاحيات وصول هذا المستخدم لأقسام النظام بشكل مخصص",
    selectAllPerms: "تحديد كل الصلاحيات",
    deselectAllPerms: "إلغاء تحديد الكل",
    perm_properties: "إدارة العقارات (إضافة / تعديل / حذف)",
    perm_clients: "إدارة العملاء والطلبات ومراحل البيع",
    perm_owners: "إدارة الملاك وبيانات التواصل",
    perm_brokers: "إدارة الوسطاء الخارجيين ونسب العمولات",
    perm_deals: "إتمام وتوثيق الصفقات وتغيير حالة العقارات",
    perm_revenue: "الاطلاع على الأرباح والتقارير المالية والعمولات",
    perm_whatsapp: "إرسال عروض الواتساب وتعديل القوالب",
    perm_reminders: "إدارة التذكيرات والمهام",
    perm_audit: "الاطلاع على سجل العمليات والأنشطة (Audit Logs)",
    perm_users: "إدارة المستخدمين والصلاحيات (للمدير العام)",

    // Deal Closing & Commission Management
    closeDealTitle: "توثيق إتمام الصفقة وحساب الأرباح والعمولات",
    closeDealDesc: "حدد سعر البيع/الإيجار الفعلي، طريقة الإتمام، إجمالي العمولة، وحصة الوسيط الخارجي لاحتساب صافي ربح شركتنا بدقة",
    actualDealPrice: "سعر الصفقة الفعلي (البيع / الإيجار)",
    saleChannel: "طريقة إتمام الصفقة (قناة البيع)",
    directDeal: "عن طريق شركتنا مباشرة (بدون وسيط خارجي)",
    externalBrokerDeal: "عن طريق وسيط خارجي / شريك (Co-Broker)",
    selectBuyerTenant: "اختر العميل المشتري / المستأجر (اختياري)",
    buyerTenantName: "اسم العميل / المشتري",
    companyCommissionGross: "إجمالي عمولة الصفقة",
    commissionPctOrAmount: "طريقة حساب عمولة الصفقة",
    percentage: "نسبة مئوية (%)",
    fixedAmount: "مبلغ مالي ثابت (ج.م)",
    externalBrokerShare: "حصة / عمولة الوسيط الخارجي",
    brokerSharePctOrAmount: "طريقة حساب حصة الوسيط الخارجي",
    netCompanyRevenue: "صافي دخل وأرباح الشركة (الداخل لخزنتنا)",
    netCompanyRevenueDesc: "المبلغ الفعلي الذي دخل لشركتنا بعد خصم عمولة الوسيط الخارجي إن وجدت",
    confirmCloseDeal: "تأكيد إتمام الصفقة وتحديث حالة العقار",
    grossCommissionLabel: "إجمالي العمولة",
    brokerPayoutLabel: "حصة الوسيط",
    netProfitLabel: "صافي ربح الشركة",
    directSaleBadge: "صفقة مباشرة",
    brokerSaleBadge: "عبر وسيط خارجي",
    dealNotesPlaceholder: "أي ملاحظات إضافية بخصوص العقد أو استلام العمولات...",
    contractType: "نوع العقد",
    dealSoldSuccess: "تم توثيق الصفقة بنجاح وحساب صافي الأرباح وتحديث حالة العقار!",
    dealSalesAgent: "مسؤول المبيعات المنفذ للصفقة (السيلز)",
    dealSalesAgentDesc: "اختر مسؤول المبيعات الذي عمل على إتمام هذه الصفقة لتُسجل في أرباحه وتقييماته، أو اتركها لنفسك إن أغلقتها مباشرة",
    dealClosedBySelf: "تمت بواسطتي مباشرة (بدون سيلز آخر)",

    // Notification Center & Actions
    notificationCenter: "مركز الإشعارات والتنبيهات التفاعلي",
    notificationsDesc: "تنبيهات فورية ومهام هامة تتطلب متابعة وإجراء مباشر",
    viewMatchesAction: "معاينة فرص التطابق الآن ⚡",
    viewRemindersAction: "متابعة المواعيد والتذكيرات 📅",
    viewClientsAction: "متابعة مراحل العملاء 👥",
    viewDealsAction: "عرض تفاصيل الصفقات 💰",
    newMatchesAlertTitle: "فرص مطابقة ذكية جديدة",
    pendingRemindersAlertTitle: "تذكيرات ومواعيد قيد الانتظار",
    activeClientsAlertTitle: "عملاء في مراحل التفاوض والاهتمام",
    newDealsAlertTitle: "أحدث الصفقات المكتملة",
    allCaughtUp: "رائع! لا توجد تنبيهات أو مهام معلقة حالياً.",
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  darkMode: boolean;
  setDarkMode: (mode: boolean) => void;
  t: (key: keyof typeof translations.en) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguageState] = useState<Language>(() => {
    return (localStorage.getItem("lang") as Language) || "ar"; // Default to Arabic as requested!
  });

  const [darkMode, setDarkModeState] = useState<boolean>(() => {
    return localStorage.getItem("darkMode") === "true";
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem("lang", lang);
  };

  const setDarkMode = (mode: boolean) => {
    setDarkModeState(mode);
    localStorage.setItem("darkMode", String(mode));
  };

  useEffect(() => {
    document.documentElement.dir = language === "ar" ? "rtl" : "ltr";
    document.documentElement.lang = language;
  }, [language]);

  useEffect(() => {
    if (darkMode) {
      document.documentElement.classList.add("dark");
    } else {
      document.documentElement.classList.remove("dark");
    }
  }, [darkMode]);

  const t = (key: keyof typeof translations.en): string => {
    return translations[language][key] || translations["en"][key] || String(key);
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, darkMode, setDarkMode, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};
